import type { Page, Action } from '@/types/miniprogram';

export class JSGenerator {
  /**
   * 生成页面完整 JS
   */
  generatePage(page: Page): string {
    let js = `// ${page.name}\n`;
    js += `// Generated by MiniProgram Studio\n\n`;

    // 生成 Page() 调用
    js += 'Page({\n';

    // 生成 data
    js += this.generateData(page);

    // 生成生命周期
    js += this.generateLifecycle(page);

    // 生成事件处理函数
    js += this.generateEventHandlers(page);

    js += '});\n';

    return js;
  }

  /**
   * 生成 data
   */
  private generateData(page: Page): string {
    let result = '  data: {\n';

    if (page.pageData && Object.keys(page.pageData).length > 0) {
      for (const [key, value] of Object.entries(page.pageData)) {
        if (typeof value === 'string') {
          result += `    ${key}: '${value}',\n`;
        } else if (typeof value === 'number' || typeof value === 'boolean') {
          result += `    ${key}: ${value},\n`;
        } else {
          result += `    ${key}: ${JSON.stringify(value)},\n`;
        }
      }
    }

    result += '  },\n\n';
    return result;
  }

  /**
   * 生成生命周期函数
   */
  private generateLifecycle(page: Page): string {
    let result = '';

    // 默认生命周期
    const lifecycles = ['onLoad', 'onShow', 'onReady', 'onHide', 'onUnload'];

    for (const lifecycle of lifecycles) {
      const event = page.lifecycleEvents?.find((e) => e.type === lifecycle);
      if (event && event.actions.length > 0) {
        result += `  ${lifecycle}(options) {\n`;
        for (const action of event.actions) {
          result += this.generateAction(action, '    ');
        }
        result += '  },\n\n';
      }
    }

    // 默认添加 onLoad（如果没有自定义）
    if (!result.includes('onLoad')) {
      result += '  onLoad(options) {\n';
      result += '    console.log("页面加载", options);\n';
      result += '  },\n\n';
    }

    // 默认添加 onShow（如果没有自定义）
    if (!result.includes('onShow')) {
      result += '  onShow() {\n';
      result += '    console.log("页面显示");\n';
      result += '  },\n\n';
    }

    return result;
  }

  /**
   * 生成事件处理函数
   */
  private generateEventHandlers(page: Page): string {
    let result = '';
    const generatedHandlers = new Set<string>();

    // 收集所有组件的事件
    const collectEvents = (components: any[]) => {
      for (const component of components) {
        if (component.events && component.events.length > 0) {
          for (const event of component.events) {
            const handlerName = `${event.trigger}Handler_${component.id.slice(0, 8)}`;
            if (!generatedHandlers.has(handlerName)) {
              generatedHandlers.add(handlerName);
              result += this.generateEventHandler(handlerName, event, component);
            }
          }
        }
        if (component.children) {
          collectEvents(component.children);
        }
      }
    };

    collectEvents(page.components || []);

    return result;
  }

  /**
   * 生成单个事件处理函数
   */
  private generateEventHandler(
    name: string,
    event: { trigger: string; actions: Action[] },
    _component: any
  ): string {
    let result = `  ${name}(e) {\n`;
    result += `    console.log("${event.trigger}事件", e);\n`;

    for (const action of event.actions) {
      result += this.generateAction(action, '    ');
    }

    result += '  },\n\n';
    return result;
  }

  /**
   * 生成动作代码
   */
  private generateAction(action: Action, indent: string): string {
    let result = '';

    switch (action.type) {
      case 'setData':
        result += `${indent}this.setData({\n`;
        for (const [key, value] of Object.entries(action.params)) {
          if (typeof value === 'string') {
            result += `${indent}  ${key}: '${value}',\n`;
          } else if (typeof value === 'number' || typeof value === 'boolean') {
            result += `${indent}  ${key}: ${value},\n`;
          } else {
            result += `${indent}  ${key}: ${JSON.stringify(value)},\n`;
          }
        }
        result += `${indent}});\n`;
        break;

      case 'navigateTo':
        result += `${indent}wx.navigateTo({\n`;
        result += `${indent}  url: '${action.params.url}'\n`;
        result += `${indent}});\n`;
        break;

      case 'redirectTo':
        result += `${indent}wx.redirectTo({\n`;
        result += `${indent}  url: '${action.params.url}'\n`;
        result += `${indent}});\n`;
        break;

      case 'switchTab':
        result += `${indent}wx.switchTab({\n`;
        result += `${indent}  url: '${action.params.url}'\n`;
        result += `${indent}});\n`;
        break;

      case 'navigateBack':
        result += `${indent}wx.navigateBack({\n`;
        result += `${indent}  delta: ${action.params.delta || 1}\n`;
        result += `${indent}});\n`;
        break;

      case 'reLaunch':
        result += `${indent}wx.reLaunch({\n`;
        result += `${indent}  url: '${action.params.url}'\n`;
        result += `${indent}});\n`;
        break;

      case 'toast':
        result += `${indent}wx.showToast({\n`;
        result += `${indent}  title: '${action.params.title || '提示'}',\n`;
        result += `${indent}  icon: '${action.params.icon || 'none'}'\n`;
        result += `${indent}});\n`;
        break;

      case 'showModal':
        result += `${indent}wx.showModal({\n`;
        result += `${indent}  title: '${action.params.title || '提示'}',\n`;
        result += `${indent}  content: '${action.params.content || ''}',\n`;
        result += `${indent}  showCancel: ${action.params.showCancel !== false}\n`;
        result += `${indent}});\n`;
        break;

      case 'showLoading':
        result += `${indent}wx.showLoading({\n`;
        result += `${indent}  title: '${action.params.title || '加载中'}'\n`;
        result += `${indent}});\n`;
        break;

      case 'hideLoading':
        result += `${indent}wx.hideLoading();\n`;
        break;

      case 'request':
        result += `${indent}wx.request({\n`;
        result += `${indent}  url: '${action.params.url}',\n`;
        result += `${indent}  method: '${action.params.method || 'GET'}',\n`;
        result += `${indent}  data: ${JSON.stringify(action.params.data || {})},\n`;
        result += `${indent}  success: (res) => {\n`;
        result += `${indent}    console.log(res);\n`;
        result += `${indent}  }\n`;
        result += `${indent}});\n`;
        break;

      case 'setStorage':
        result += `${indent}wx.setStorageSync('${action.params.key}', ${JSON.stringify(action.params.value)});\n`;
        break;

      case 'getStorage':
        result += `${indent}const value = wx.getStorageSync('${action.params.key}');\n`;
        result += `${indent}console.log(value);\n`;
        break;

      case 'custom':
        result += `${indent}// 自定义代码\n`;
        if (action.params.code) {
          result += `${indent}${action.params.code}\n`;
        }
        break;

      default:
        result += `${indent}// TODO: 实现动作 ${action.type}\n`;
    }

    return result;
  }

  /**
   * 生成 app.js
   */
  generateAppJs(): string {
    return `/* App.js */
/* Generated by MiniProgram Studio */

App({
  onLaunch() {
    console.log('小程序启动');
  },

  onShow() {
    console.log('小程序显示');
  },

  onHide() {
    console.log('小程序隐藏');
  },

  onError(msg) {
    console.error('小程序错误:', msg);
  },

  globalData: {}
});
`;
  }

  /**
   * 生成 app.json
   */
  generateAppJson(project: any): string {
    return JSON.stringify({
      pages: project.config.pages || [],
      window: project.config.window || {},
      tabBar: project.config.tabBar,
      networkTimeout: project.config.networkTimeout,
      debug: project.config.debug || false,
    }, null, 2);
  }

  /**
   * 生成页面配置 JSON
   */
  generatePageJson(page: Page): string {
    return JSON.stringify({
      navigationBarTitleText: page.config?.navigationBarTitleText || page.name,
      navigationBarBackgroundColor: page.config?.navigationBarBackgroundColor,
      navigationBarTextStyle: page.config?.navigationBarTextStyle || 'black',
      backgroundColor: page.config?.backgroundColor,
      enablePullDownRefresh: page.config?.enablePullDownRefresh || false,
      usingComponents: page.config?.usingComponents || {},
    }, null, 2);
  }
}

export default new JSGenerator();
