import type { ComponentDefinition, ComponentCategory } from '@/types/miniprogram';

// 微信小程序内置组件定义
export const BUILTIN_COMPONENTS: ComponentDefinition[] = [
  // 容器组件
  {
    id: 'view',
    type: 'view',
    name: '视图容器',
    icon: 'BorderOutlined',
    category: 'container',
    defaultProps: {},
    defaultStyles: {
      width: '100%',
      minHeight: '50px',
      padding: '10px',
    },
    propDefinitions: [
      { name: 'hover-class', label: '点击态类名', type: 'string', defaultValue: '' },
      { name: 'hover-start-time', label: '按住后多久出现点击态', type: 'number', defaultValue: 50 },
      { name: 'hover-stay-time', label: '松开后点击态保留时间', type: 'number', defaultValue: 400 },
    ],
    styleDefinitions: [],
    events: ['tap', 'longpress', 'touchstart', 'touchmove', 'touchend'],
    allowChildren: true,
    isCustom: false,
  },
  {
    id: 'scroll-view',
    type: 'scroll-view',
    name: '滚动视图',
    icon: 'VerticalAlignMiddleOutlined',
    category: 'container',
    defaultProps: {
      'scroll-y': true,
    },
    defaultStyles: {
      width: '100%',
      height: '300px',
    },
    propDefinitions: [
      { name: 'scroll-x', label: '允许横向滚动', type: 'boolean', defaultValue: false },
      { name: 'scroll-y', label: '允许纵向滚动', type: 'boolean', defaultValue: true },
      { name: 'upper-threshold', label: '距顶/左多远触发scrolltoupper', type: 'number', defaultValue: 50 },
      { name: 'lower-threshold', label: '距底/右多远触发scrolltolower', type: 'number', defaultValue: 50 },
      { name: 'scroll-top', label: '纵向滚动条位置', type: 'number', defaultValue: 0 },
      { name: 'scroll-left', label: '横向滚动条位置', type: 'number', defaultValue: 0 },
      { name: 'enable-back-to-top', label: '点击状态栏回到顶部', type: 'boolean', defaultValue: false },
    ],
    styleDefinitions: [],
    events: ['scroll', 'scrolltoupper', 'scrolltolower'],
    allowChildren: true,
    isCustom: false,
  },
  {
    id: 'swiper',
    type: 'swiper',
    name: '轮播图',
    icon: 'SwitcherOutlined',
    category: 'container',
    defaultProps: {
      'indicator-dots': true,
      autoplay: true,
      circular: true,
    },
    defaultStyles: {
      width: '100%',
      height: '200px',
    },
    propDefinitions: [
      { name: 'indicator-dots', label: '显示指示点', type: 'boolean', defaultValue: true },
      { name: 'indicator-color', label: '指示点颜色', type: 'color', defaultValue: 'rgba(0,0,0,.3)' },
      { name: 'indicator-active-color', label: '当前选中指示点颜色', type: 'color', defaultValue: '#000000' },
      { name: 'autoplay', label: '自动播放', type: 'boolean', defaultValue: false },
      { name: 'current', label: '当前所在页面索引', type: 'number', defaultValue: 0 },
      { name: 'interval', label: '自动切换时间间隔', type: 'number', defaultValue: 5000 },
      { name: 'duration', label: '滑动动画时长', type: 'number', defaultValue: 500 },
      { name: 'circular', label: '衔接滑动', type: 'boolean', defaultValue: false },
      { name: 'vertical', label: '纵向滑动', type: 'boolean', defaultValue: false },
    ],
    styleDefinitions: [],
    events: ['change', 'transition', 'animationfinish'],
    allowChildren: true,
    isCustom: false,
  },

  // 基础组件
  {
    id: 'text',
    type: 'text',
    name: '文本',
    icon: 'FontSizeOutlined',
    category: 'basic',
    defaultProps: {
      content: '文本内容',
      selectable: false,
      space: '',
      decode: false,
    },
    defaultStyles: {
      fontSize: '14px',
      color: '#333333',
      fontWeight: 'normal',
      fontStyle: 'normal',
      textAlign: 'left',
      lineHeight: '1.5',
      textDecoration: 'none',
    },
    propDefinitions: [
      { name: 'content', label: '文本内容', type: 'string', defaultValue: '文本内容' },
      { name: 'selectable', label: '是否可选', type: 'boolean', defaultValue: false },
      { name: 'space', label: '显示连续空格', type: 'select', defaultValue: '', options: [
        { label: '无', value: '' },
        { label: '中文字符空格', value: 'ensp' },
        { label: '中文字符空格一半', value: 'emsp' },
        { label: '根据字体设置空格', value: 'nbsp' },
      ]},
      { name: 'decode', label: '是否解码', type: 'boolean', defaultValue: false },
    ],
    styleDefinitions: [
      { name: 'fontSize', label: '字体大小', type: 'string', defaultValue: '14px', placeholder: '如: 14px, 1rem' },
      { name: 'color', label: '文字颜色', type: 'color', defaultValue: '#333333' },
      { name: 'fontWeight', label: '字体粗细', type: 'select', defaultValue: 'normal', options: [
        { label: '正常', value: 'normal' },
        { label: '粗体', value: 'bold' },
        { label: '更粗', value: 'bolder' },
        { label: '更细', value: 'lighter' },
        { label: '100', value: '100' },
        { label: '200', value: '200' },
        { label: '300', value: '300' },
        { label: '400', value: '400' },
        { label: '500', value: '500' },
        { label: '600', value: '600' },
        { label: '700', value: '700' },
        { label: '800', value: '800' },
        { label: '900', value: '900' },
      ]},
      { name: 'fontStyle', label: '字体样式', type: 'select', defaultValue: 'normal', options: [
        { label: '正常', value: 'normal' },
        { label: '斜体', value: 'italic' },
        { label: '倾斜', value: 'oblique' },
      ]},
      { name: 'textAlign', label: '文本对齐', type: 'select', defaultValue: 'left', options: [
        { label: '左对齐', value: 'left' },
        { label: '居中', value: 'center' },
        { label: '右对齐', value: 'right' },
        { label: '两端对齐', value: 'justify' },
      ]},
      { name: 'lineHeight', label: '行高', type: 'string', defaultValue: '1.5', placeholder: '如: 1.5, 20px' },
      { name: 'textDecoration', label: '文本装饰', type: 'select', defaultValue: 'none', options: [
        { label: '无', value: 'none' },
        { label: '下划线', value: 'underline' },
        { label: '删除线', value: 'line-through' },
        { label: '上划线', value: 'overline' },
      ]},
      { name: 'letterSpacing', label: '字间距', type: 'string', defaultValue: 'normal', placeholder: '如: 1px, 0.1em' },
      { name: 'textShadow', label: '文字阴影', type: 'string', defaultValue: 'none', placeholder: '如: 2px 2px 4px rgba(0,0,0,0.5)' },
    ],
    events: ['tap', 'longpress'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'icon',
    type: 'icon',
    name: '图标',
    icon: 'StarOutlined',
    category: 'basic',
    defaultProps: {
      type: 'success',
      size: 23,
    },
    defaultStyles: {},
    propDefinitions: [
      { name: 'type', label: '图标类型', type: 'select', defaultValue: 'success', options: [
        { label: 'success', value: 'success' },
        { label: 'success_no_circle', value: 'success_no_circle' },
        { label: 'info', value: 'info' },
        { label: 'warn', value: 'warn' },
        { label: 'waiting', value: 'waiting' },
        { label: 'cancel', value: 'cancel' },
        { label: 'download', value: 'download' },
        { label: 'search', value: 'search' },
        { label: 'clear', value: 'clear' },
      ]},
      { name: 'size', label: '大小', type: 'number', defaultValue: 23 },
      { name: 'color', label: '颜色', type: 'color', defaultValue: '' },
    ],
    styleDefinitions: [],
    events: ['tap'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'progress',
    type: 'progress',
    name: '进度条',
    icon: 'LineOutlined',
    category: 'basic',
    defaultProps: {
      percent: 50,
      'show-info': true,
    },
    defaultStyles: {
      width: '100%',
    },
    propDefinitions: [
      { name: 'percent', label: '百分比', type: 'number', defaultValue: 0, min: 0, max: 100 },
      { name: 'show-info', label: '显示百分比', type: 'boolean', defaultValue: false },
      { name: 'border-radius', label: '圆角大小', type: 'number', defaultValue: 0 },
      { name: 'font-size', label: '字体大小', type: 'number', defaultValue: 16 },
      { name: 'stroke-width', label: '进度条宽度', type: 'number', defaultValue: 6 },
      { name: 'color', label: '进度条颜色', type: 'color', defaultValue: '#09BB07' },
      { name: 'activeColor', label: '已选进度条颜色', type: 'color', defaultValue: '#09BB07' },
      { name: 'backgroundColor', label: '未选进度条颜色', type: 'color', defaultValue: '#EBEBEB' },
      { name: 'active', label: '进度条动画', type: 'boolean', defaultValue: false },
    ],
    styleDefinitions: [],
    events: ['activeend'],
    allowChildren: false,
    isCustom: false,
  },

  // 表单组件
  {
    id: 'button',
    type: 'button',
    name: '按钮',
    icon: 'BorderOuterOutlined',
    category: 'form',
    defaultProps: {
      content: '按钮',
      type: 'primary',
    },
    defaultStyles: {},
    propDefinitions: [
      { name: 'content', label: '按钮文字', type: 'string', defaultValue: '按钮' },
      { name: 'type', label: '按钮类型', type: 'select', defaultValue: 'default', options: [
        { label: '默认', value: 'default' },
        { label: '主要', value: 'primary' },
        { label: '警告', value: 'warn' },
      ]},
      { name: 'size', label: '按钮大小', type: 'select', defaultValue: 'default', options: [
        { label: '默认', value: 'default' },
        { label: '小', value: 'mini' },
      ]},
      { name: 'plain', label: '镂空', type: 'boolean', defaultValue: false },
      { name: 'disabled', label: '禁用', type: 'boolean', defaultValue: false },
      { name: 'loading', label: '加载中', type: 'boolean', defaultValue: false },
      { name: 'form-type', label: '表单类型', type: 'select', defaultValue: '', options: [
        { label: '无', value: '' },
        { label: '提交', value: 'submit' },
        { label: '重置', value: 'reset' },
      ]},
      { name: 'open-type', label: '开放能力', type: 'select', defaultValue: '', options: [
        { label: '无', value: '' },
        { label: '打开客服会话', value: 'contact' },
        { label: '分享', value: 'share' },
        { label: '获取手机号', value: 'getPhoneNumber' },
        { label: '获取用户信息', value: 'getUserInfo' },
        { label: '打开App', value: 'launchApp' },
        { label: '打开设置', value: 'openSetting' },
        { label: '意见反馈', value: 'feedback' },
      ]},
    ],
    styleDefinitions: [],
    events: ['tap', 'getuserinfo', 'contact', 'getphonenumber', 'error', 'opensetting', 'launchapp'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'input',
    type: 'input',
    name: '输入框',
    icon: 'EditOutlined',
    category: 'form',
    defaultProps: {
      placeholder: '请输入',
    },
    defaultStyles: {
      width: '100%',
      height: '40px',
      padding: '0 10px',
      border: '1px solid #ddd',
      borderRadius: '4px',
    },
    propDefinitions: [
      { name: 'value', label: '输入框的值', type: 'expression', defaultValue: '' },
      { name: 'type', label: '输入类型', type: 'select', defaultValue: 'text', options: [
        { label: '文本', value: 'text' },
        { label: '数字', value: 'number' },
        { label: '身份证', value: 'idcard' },
        { label: '带小数点数字', value: 'digit' },
        { label: '昵称', value: 'nickname' },
      ]},
      { name: 'password', label: '是否密码类型', type: 'boolean', defaultValue: false },
      { name: 'placeholder', label: '占位符', type: 'string', defaultValue: '' },
      { name: 'placeholder-style', label: '占位符样式', type: 'string', defaultValue: '' },
      { name: 'maxlength', label: '最大输入长度', type: 'number', defaultValue: 140 },
      { name: 'disabled', label: '禁用', type: 'boolean', defaultValue: false },
      { name: 'focus', label: '获取焦点', type: 'boolean', defaultValue: false },
      { name: 'confirm-type', label: '键盘右下角按钮文字', type: 'select', defaultValue: 'done', options: [
        { label: '发送', value: 'send' },
        { label: '搜索', value: 'search' },
        { label: '下一个', value: 'next' },
        { label: '前往', value: 'go' },
        { label: '完成', value: 'done' },
      ]},
    ],
    styleDefinitions: [],
    events: ['input', 'focus', 'blur', 'confirm'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'textarea',
    type: 'textarea',
    name: '多行输入',
    icon: 'AlignLeftOutlined',
    category: 'form',
    defaultProps: {
      placeholder: '请输入',
    },
    defaultStyles: {
      width: '100%',
      height: '100px',
      padding: '10px',
      border: '1px solid #ddd',
      borderRadius: '4px',
    },
    propDefinitions: [
      { name: 'value', label: '输入框的值', type: 'expression', defaultValue: '' },
      { name: 'placeholder', label: '占位符', type: 'string', defaultValue: '' },
      { name: 'maxlength', label: '最大输入长度', type: 'number', defaultValue: 140 },
      { name: 'disabled', label: '禁用', type: 'boolean', defaultValue: false },
      { name: 'auto-height', label: '自动增高', type: 'boolean', defaultValue: false },
      { name: 'focus', label: '获取焦点', type: 'boolean', defaultValue: false },
      { name: 'show-confirm-bar', label: '显示键盘上方带有完成按钮那一栏', type: 'boolean', defaultValue: true },
    ],
    styleDefinitions: [],
    events: ['input', 'focus', 'blur', 'confirm', 'linechange'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'checkbox',
    type: 'checkbox',
    name: '复选框',
    icon: 'CheckSquareOutlined',
    category: 'form',
    defaultProps: {
      value: 'checkbox',
    },
    defaultStyles: {},
    propDefinitions: [
      { name: 'value', label: '标识', type: 'string', defaultValue: '' },
      { name: 'disabled', label: '禁用', type: 'boolean', defaultValue: false },
      { name: 'checked', label: '是否选中', type: 'boolean', defaultValue: false },
      { name: 'color', label: '颜色', type: 'color', defaultValue: '#09BB07' },
    ],
    styleDefinitions: [],
    events: ['tap'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'radio',
    type: 'radio',
    name: '单选框',
    icon: 'CheckCircleOutlined',
    category: 'form',
    defaultProps: {
      value: 'radio',
    },
    defaultStyles: {},
    propDefinitions: [
      { name: 'value', label: '标识', type: 'string', defaultValue: '' },
      { name: 'disabled', label: '禁用', type: 'boolean', defaultValue: false },
      { name: 'checked', label: '是否选中', type: 'boolean', defaultValue: false },
      { name: 'color', label: '颜色', type: 'color', defaultValue: '#09BB07' },
    ],
    styleDefinitions: [],
    events: ['tap'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'switch',
    type: 'switch',
    name: '开关',
    icon: 'PoweroffOutlined',
    category: 'form',
    defaultProps: {},
    defaultStyles: {},
    propDefinitions: [
      { name: 'checked', label: '是否选中', type: 'boolean', defaultValue: false },
      { name: 'disabled', label: '禁用', type: 'boolean', defaultValue: false },
      { name: 'type', label: '样式', type: 'select', defaultValue: 'switch', options: [
        { label: '开关', value: 'switch' },
        { label: '复选框', value: 'checkbox' },
      ]},
      { name: 'color', label: '颜色', type: 'color', defaultValue: '#04BE02' },
    ],
    styleDefinitions: [],
    events: ['change'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'slider',
    type: 'slider',
    name: '滑动选择器',
    icon: 'ControlOutlined',
    category: 'form',
    defaultProps: {
      value: 50,
    },
    defaultStyles: {
      width: '100%',
    },
    propDefinitions: [
      { name: 'min', label: '最小值', type: 'number', defaultValue: 0 },
      { name: 'max', label: '最大值', type: 'number', defaultValue: 100 },
      { name: 'step', label: '步长', type: 'number', defaultValue: 1 },
      { name: 'disabled', label: '禁用', type: 'boolean', defaultValue: false },
      { name: 'value', label: '当前值', type: 'number', defaultValue: 0 },
      { name: 'show-value', label: '显示当前值', type: 'boolean', defaultValue: false },
      { name: 'activeColor', label: '已选颜色', type: 'color', defaultValue: '#1aad19' },
      { name: 'backgroundColor', label: '背景颜色', type: 'color', defaultValue: '#e9e9e9' },
      { name: 'block-size', label: '滑块大小', type: 'number', defaultValue: 28, min: 12, max: 28 },
      { name: 'block-color', label: '滑块颜色', type: 'color', defaultValue: '#ffffff' },
    ],
    styleDefinitions: [],
    events: ['change', 'changing'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'picker',
    type: 'picker',
    name: '选择器',
    icon: 'DownOutlined',
    category: 'form',
    defaultProps: {
      mode: 'selector',
    },
    defaultStyles: {},
    propDefinitions: [
      { name: 'mode', label: '选择器类型', type: 'select', defaultValue: 'selector', options: [
        { label: '普通选择器', value: 'selector' },
        { label: '多列选择器', value: 'multiSelector' },
        { label: '时间选择器', value: 'time' },
        { label: '日期选择器', value: 'date' },
        { label: '省市区选择器', value: 'region' },
      ]},
      { name: 'disabled', label: '禁用', type: 'boolean', defaultValue: false },
    ],
    styleDefinitions: [],
    events: ['change', 'cancel'],
    allowChildren: true,
    isCustom: false,
  },

  // 媒体组件
  {
    id: 'image',
    type: 'image',
    name: '图片',
    icon: 'PictureOutlined',
    category: 'media',
    defaultProps: {
      src: '',
      mode: 'aspectFill',
    },
    defaultStyles: {
      width: '100px',
      height: '100px',
    },
    propDefinitions: [
      { name: 'src', label: '图片地址', type: 'image', defaultValue: '' },
      { name: 'mode', label: '缩放裁剪模式', type: 'select', defaultValue: 'scaleToFill', options: [
        { label: '缩放', value: 'scaleToFill' },
        { label: '保持纵横比缩放', value: 'aspectFit' },
        { label: '保持纵横比填充', value: 'aspectFill' },
        { label: '宽度不变', value: 'widthFix' },
        { label: '高度不变', value: 'heightFix' },
        { label: '裁剪 top', value: 'top' },
        { label: '裁剪 bottom', value: 'bottom' },
        { label: '裁剪 center', value: 'center' },
        { label: '裁剪 left', value: 'left' },
        { label: '裁剪 right', value: 'right' },
      ]},
      { name: 'lazy-load', label: '懒加载', type: 'boolean', defaultValue: false },
      { name: 'show-menu-by-longpress', label: '长按显示菜单', type: 'boolean', defaultValue: false },
    ],
    styleDefinitions: [],
    events: ['tap', 'load', 'error'],
    allowChildren: false,
    isCustom: false,
  },
  {
    id: 'video',
    type: 'video',
    name: '视频',
    icon: 'PlaySquareOutlined',
    category: 'media',
    defaultProps: {
      src: '',
    },
    defaultStyles: {
      width: '100%',
      height: '200px',
    },
    propDefinitions: [
      { name: 'src', label: '视频地址', type: 'string', defaultValue: '' },
      { name: 'poster', label: '封面图', type: 'image', defaultValue: '' },
      { name: 'controls', label: '显示控制栏', type: 'boolean', defaultValue: true },
      { name: 'autoplay', label: '自动播放', type: 'boolean', defaultValue: false },
      { name: 'loop', label: '循环播放', type: 'boolean', defaultValue: false },
      { name: 'muted', label: '静音', type: 'boolean', defaultValue: false },
      { name: 'show-fullscreen-btn', label: '显示全屏按钮', type: 'boolean', defaultValue: true },
      { name: 'show-play-btn', label: '显示播放按钮', type: 'boolean', defaultValue: true },
      { name: 'enable-progress-gesture', label: '启用进度手势', type: 'boolean', defaultValue: true },
    ],
    styleDefinitions: [],
    events: ['play', 'pause', 'ended', 'timeupdate', 'fullscreenchange', 'waiting', 'error'],
    allowChildren: false,
    isCustom: false,
  },

  // 导航组件
  {
    id: 'navigator',
    type: 'navigator',
    name: '导航',
    icon: 'LinkOutlined',
    category: 'navigation',
    defaultProps: {
      url: '',
      content: '跳转链接',
    },
    defaultStyles: {
      color: '#1677ff',
    },
    propDefinitions: [
      { name: 'content', label: '显示文字', type: 'string', defaultValue: '跳转链接' },
      { name: 'url', label: '跳转地址', type: 'string', defaultValue: '' },
      { name: 'open-type', label: '跳转方式', type: 'select', defaultValue: 'navigate', options: [
        { label: 'navigate', value: 'navigate' },
        { label: 'redirect', value: 'redirect' },
        { label: 'switchTab', value: 'switchTab' },
        { label: 'reLaunch', value: 'reLaunch' },
        { label: 'navigateBack', value: 'navigateBack' },
      ]},
      { name: 'delta', label: '返回层数', type: 'number', defaultValue: 1 },
      { name: 'hover-class', label: '点击态类名', type: 'string', defaultValue: 'navigator-hover' },
    ],
    styleDefinitions: [],
    events: ['success', 'fail', 'complete'],
    allowChildren: true,
    isCustom: false,
  },

  // 游戏控制组件
  {
    id: 'joystick',
    type: 'joystick',
    name: '虚拟摇杆',
    icon: 'ControlOutlined',
    category: 'custom',
    defaultProps: {
      targetId: '', // 控制的目标组件ID
      speed: 3, // 移动速度
      size: 120, // 摇杆大小
    },
    defaultStyles: {
      opacity: 0.6,
    },
    propDefinitions: [
      { name: 'targetId', label: '控制目标', type: 'string', defaultValue: '', placeholder: '留空则控制所有player角色' },
      { name: 'speed', label: '移动速度', type: 'number', defaultValue: 3, min: 1, max: 20 },
      { name: 'size', label: '摇杆大小', type: 'number', defaultValue: 120, min: 80, max: 200 },
      { name: 'opacity', label: '透明度', type: 'number', defaultValue: 0.6, min: 0.1, max: 1, step: 0.1 },
    ],
    styleDefinitions: [],
    events: [],
    allowChildren: false,
    isCustom: true,
  },
];

// 组件分类
export const COMPONENT_CATEGORIES: { key: ComponentCategory; label: string; icon: string }[] = [
  { key: 'container', label: '容器', icon: 'AppstoreOutlined' },
  { key: 'basic', label: '基础', icon: 'BuildOutlined' },
  { key: 'form', label: '表单', icon: 'FormOutlined' },
  { key: 'media', label: '媒体', icon: 'PlayCircleOutlined' },
  { key: 'navigation', label: '导航', icon: 'RightOutlined' },
  { key: 'custom', label: '自定义', icon: 'CodeOutlined' },
];

// 根据分类获取组件
export const getComponentsByCategory = (category: ComponentCategory): ComponentDefinition[] => {
  return BUILTIN_COMPONENTS.filter((comp) => comp.category === category);
};

// 根据类型获取组件定义
export const getComponentDefinition = (type: string): ComponentDefinition | undefined => {
  return BUILTIN_COMPONENTS.find((comp) => comp.type === type);
};
